Gh actions test
OSU-Sustainability-Office/osu_carbon_calculator_update_project pull request #34
Opened 2022-12-26 23:29 UTC by solderq35

I set up github pages and s3 gh actions workflow like energy-dashboard, but I get a weird cors error on the console, and I can't seem to login / view historical data.

2022-12-27 22:36 UTC, MilanDonhowe commented on packaged.yaml
>        Events:
We should probably delete this file, I think it's leftover from an old build command.

2022-12-27 22:36 UTC, MilanDonhowe commented on backend/template.yaml
>        Events:
We should probably update the lambda common layer reference

2022-12-27 22:38 UTC, MilanDonhowe requested changes
Looking good so far, few changes we'll want to make before merging:

- [ ] delete packaged.yaml
- [ ] update common layer reference (should match dashboard's reference in its template.yaml)

And after that I think we should be good to merge the CI changes

2022-12-29 07:03 UTC, solderq35 commented
I couldn't figure out how to fix the login issues but I removed the packaged.yaml, updated lambda layer reference, and added vue store debugging.

2022-12-29 07:03 UTC, merged